# Configuracion personalizada del servidor Zabbix para Proyecto 7.
# Este archivo se monta como volumen en /etc/zabbix/zabbix_server.conf.d/.
Timeout=5
UnreachablePeriod=45
UnavailableDelay=30
UnreachableDelay=30

